"use client";

import Image from "next/image";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowDownRight, ArrowUpRight, Check, ChevronDown, Dumbbell, MessageCircle, Play, Salad, ScanLine, Sparkles, TrendingUp } from "lucide-react";
import { useState } from "react";
import type { LucideIcon } from "lucide-react";

const images = { hero: "/images/hero.png", about: "/images/about.png", contact: "/images/contact.png" };
const benefits: [LucideIcon, string, string][] = [
  [Dumbbell,"Индивидуальная программа","Тренировки выстраиваются вокруг вашей цели, графика и доступного оборудования."],
  [Salad,"Рекомендации по питанию","Понятная система питания без крайностей и временных решений."],
  [TrendingUp,"Контроль прогресса","Отслеживаем изменения и опираемся на данные, а не на ощущения."],
  [Play,"Проверка техники","Разбираю видео упражнений, чтобы тренировки были безопаснее и точнее."],
  [MessageCircle,"Постоянная связь","Вы не остаётесь с программой один на один между отчётами."],
  [ScanLine,"Корректировка плана","Регулярно обновляю нагрузку и питание, когда меняются условия и результат."],
];
const plans = [
  { name:"Старт", price:"150", intro:"Для самостоятельного и понятного старта.", items:["Индивидуальная программа тренировок","Рекомендации по питанию","Контроль прогресса","Корректировка программы","Поддержка в мессенджере"] },
  { name:"Стандарт", price:"250", intro:"Больше внимания к деталям и обратной связи.", featured:true, items:["Всё из тарифа «Старт»","Проверка техники упражнений","Разбор питания","Более частая обратная связь","Дополнительные корректировки"] },
  { name:"Премиум", price:"400", intro:"Для тех, кому важен приоритет и максимальная вовлечённость.", items:["Всё из «Стандарт»","Приоритетная поддержка","Неограниченные консультации в рабочее время","Индивидуальная стратегия достижения цели"] },
];
const faqs = [["Можно ли заниматься дома?","Да. Программа учитывает ваше оборудование: от тренировок с собственным весом до полноценного зала."],["Подходит ли сопровождение новичкам?","Да. Нагрузка и объяснения подстраиваются под ваш текущий опыт, поэтому начинать можно без подготовки."],["Нужно ли считать калории?","Не всегда. Мы выбираем формат, который помогает стабильно двигаться к цели и не перегружает повседневную жизнь."],["Как происходит общение?","Основная связь — в мессенджере. Вы отправляете отчёты и вопросы, а я даю обратную связь в согласованном формате."],["Как быстро я получу программу?","После консультации, анкеты, фото и замеров подготовка программы обычно занимает несколько рабочих дней."]];
const rise = { hidden:{opacity:0,y:22}, show:{opacity:1,y:0} };

export default function Home() {
 const [open,setOpen]=useState<number|null>(0);
 return <main>
  <section className="relative min-h-screen overflow-hidden bg-neutral-900 text-white">
   <Image src={images.hero} alt="Константин Ефремов в тренировочном зале" fill priority sizes="100vw" className="object-cover object-[52%_58%] opacity-80 sm:object-[52%_52%]" />
   <div className="absolute inset-0 bg-gradient-to-b from-black/45 via-black/15 to-black/65" />
   <nav className="shell relative z-10 flex items-center justify-between py-7"><a href="#top" className="text-lg font-bold tracking-[-.06em]">KE<span className="font-normal"> Fitness</span></a><a href="#contact" className="hidden text-sm text-white/80 sm:block">Связаться <ArrowUpRight className="inline h-4 w-4"/></a></nav>
   <motion.div initial="hidden" animate="show" transition={{staggerChildren:.12}} className="shell relative z-10 flex min-h-[calc(100vh-86px)] max-w-5xl flex-col items-center justify-center pb-20 text-center">
    <motion.p variants={rise} transition={{duration:.7}} className="eyebrow text-white/70">Персональное онлайн-сопровождение</motion.p>
    <motion.h1 variants={rise} transition={{duration:.75}} className="display mt-6 text-[clamp(64px,12vw,158px)] font-semibold">Train Smart.<br/>Get Results.</motion.h1>
    <motion.p variants={rise} transition={{duration:.75}} className="mt-8 max-w-xl text-base leading-7 text-white/80 sm:text-lg">Индивидуальные программы тренировок и питания с постоянной поддержкой — независимо от страны проживания.</motion.p>
    <motion.div variants={rise} transition={{duration:.75}} className="mt-9 flex flex-col gap-3 sm:flex-row"><a className="btn btn-light" href="#contact">Начать сопровождение <ArrowDownRight size={17}/></a><a className="btn border border-white/35 bg-white/10 text-white backdrop-blur-sm" href="#plans">Посмотреть тарифы</a></motion.div>
   </motion.div>
   <div className="absolute bottom-7 left-1/2 z-10 -translate-x-1/2 text-[10px] tracking-[.18em] text-white/60">SCROLL TO EXPLORE</div>
  </section>

  <section className="shell py-28 sm:py-40"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="eyebrow">Подход</p><h2 className="display mt-5 text-5xl font-semibold sm:text-7xl">План, который<br/>работает в жизни.</h2></div><p className="max-w-xl self-end text-lg leading-8 text-neutral-600">Без универсальных схем. Мы берём за основу вашу цель, реальный ритм жизни и стартовую точку — затем спокойно и последовательно выстраиваем результат.</p></div>
   <div className="grid-line mt-20 grid border-t border-neutral-200 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(([Icon,title,text],i)=><motion.article key={title as string} initial="hidden" whileInView="show" viewport={{once:true,amount:.2}} variants={rise} transition={{delay:i*.06,duration:.55}} className="min-h-64 border-b border-neutral-200 px-0 py-8 sm:px-7 sm:py-10 lg:px-9"><Icon strokeWidth={1.4} className="h-6 w-6"/><h3 className="mt-14 text-xl font-medium tracking-[-.03em]">{title}</h3><p className="mt-3 max-w-xs text-sm leading-6 text-neutral-500">{text}</p></motion.article>)}</div>
  </section>

  <section id="about" className="bg-[#f5f5f3] py-20 sm:py-28"><div className="shell grid items-center gap-12 lg:grid-cols-2 lg:gap-20"><div className="relative aspect-[4/5] overflow-hidden bg-neutral-200"><Image src={images.about} alt="Константин Ефремов у тренировочной стойки" fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover object-[52%_38%]"/></div><div><p className="eyebrow">Обо мне</p><h2 className="display mt-5 text-5xl font-semibold sm:text-7xl">Константин<br/>Ефремов</h2><p className="mt-5 text-lg font-medium">Персональный тренер.</p><p className="mt-9 max-w-lg text-base leading-8 text-neutral-600">Я помогаю людям похудеть, набрать мышечную массу, стать сильнее и улучшить качество жизни благодаря индивидуальному подходу, грамотным тренировкам и постоянному сопровождению.</p><a href="#contact" className="mt-10 inline-flex items-center gap-2 border-b border-black pb-1 text-sm font-semibold">Обсудить вашу цель <ArrowUpRight size={16}/></a></div></div></section>

  <section className="shell py-28 sm:py-40"><div className="max-w-3xl"><p className="eyebrow">Процесс</p><h2 className="display mt-5 text-5xl font-semibold sm:text-7xl">Чёткий путь<br/>без лишнего.</h2></div><div className="mt-20 border-t border-neutral-200">{["Консультация","Анкета","Фото и замеры","Индивидуальная программа","Еженедельный контроль","Достижение результата"].map((step,i)=><motion.div initial={{opacity:0,x:-16}} whileInView={{opacity:1,x:0}} viewport={{once:true}} transition={{delay:i*.05}} className="group flex items-center justify-between border-b border-neutral-200 py-6 sm:py-8" key={step}><span className="w-14 text-xs text-neutral-400">0{i+1}</span><h3 className="mr-auto text-xl tracking-[-.03em] sm:text-3xl">{step}</h3><ArrowDownRight className="h-5 w-5 transition-transform group-hover:translate-x-1 group-hover:translate-y-1" strokeWidth={1.3}/></motion.div>)}</div></section>

  <section id="plans" className="bg-[#171717] py-28 text-white sm:py-40"><div className="shell"><div className="flex flex-col justify-between gap-7 sm:flex-row"><div><p className="eyebrow text-white/50">Тарифы</p><h2 className="display mt-5 text-5xl font-semibold sm:text-7xl">Выберите формат<br/>работы.</h2></div><p className="max-w-xs self-end text-sm leading-6 text-white/55">Все тарифы включают персональный подход. Можно начать с формата, который комфортен сейчас.</p></div><div className="mt-16 grid gap-4 lg:grid-cols-3">{plans.map(plan=><article key={plan.name} className={`relative flex min-h-[500px] flex-col rounded-2xl border p-7 sm:p-9 ${plan.featured?"border-white bg-white text-[#171717]":"border-white/15 bg-white/[.045]"}`}>{plan.featured&&<span className="absolute right-6 top-6 rounded-full bg-[#171717] px-3 py-1 text-[10px] font-bold uppercase tracking-wider text-white">Самый популярный</span>}<h3 className="text-xl">{plan.name}</h3><p className={`mt-3 text-sm leading-6 ${plan.featured?"text-neutral-500":"text-white/50"}`}>{plan.intro}</p><p className="mt-10 text-5xl tracking-[-.06em]">{plan.price}<span className="ml-1 text-base tracking-normal">€/месяц</span></p><ul className="mt-10 space-y-3">{plan.items.map(item=><li key={item} className={`flex gap-3 text-sm leading-5 ${plan.featured?"text-neutral-700":"text-white/70"}`}><Check className="mt-0.5 h-4 w-4 shrink-0" strokeWidth={1.6}/>{item}</li>)}</ul><a href="#contact" className={`btn mt-auto ${plan.featured?"btn-dark":"border border-white/30 text-white"}`}>Выбрать тариф <ArrowDownRight size={16}/></a></article>)}</div></div></section>

  <section className="shell py-28 sm:py-40"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">FAQ</p><h2 className="display mt-5 text-5xl font-semibold sm:text-7xl">Частые<br/>вопросы.</h2></div><div className="border-t border-neutral-200">{faqs.map(([q,a],i)=><div className="border-b border-neutral-200" key={q}><button onClick={()=>setOpen(open===i?null:i)} className="flex w-full items-center justify-between gap-6 py-6 text-left text-lg tracking-[-.025em] sm:text-xl"><span>{q}</span><ChevronDown className={`h-5 w-5 shrink-0 transition-transform ${open===i?"rotate-180":""}`}/></button><AnimatePresence>{open===i&&<motion.div initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden"><p className="max-w-xl pb-6 text-sm leading-7 text-neutral-500">{a}</p></motion.div>}</AnimatePresence></div>)}</div></div></section>

  <section id="contact" className="relative min-h-[680px] overflow-hidden bg-black text-white"><Image src={images.contact} alt="Константин Ефремов в зале" fill sizes="100vw" className="object-cover object-[52%_31%] opacity-55 sm:object-[52%_36%]"/><div className="absolute inset-0 bg-black/50"/><div className="shell relative z-10 flex min-h-[680px] flex-col justify-between py-10 sm:py-14"><div className="flex items-center justify-between"><span className="font-bold tracking-[-.06em]">KE Fitness</span><span className="text-xs text-white/60">Онлайн · весь мир</span></div><div><p className="eyebrow text-white/65">Следующий шаг</p><h2 className="display mt-5 max-w-3xl text-6xl font-semibold sm:text-8xl">Готовы<br/>начать?</h2><p className="mt-7 max-w-md leading-7 text-white/75">Напишите в удобный мессенджер. На первой консультации разберём вашу цель, условия и подходящий формат работы.</p><div className="mt-9 flex flex-wrap gap-3"><a className="btn btn-light" href="https://t.me/efremovtrainer" target="_blank">Telegram <ArrowUpRight size={16}/></a><a className="btn border border-white/35 bg-white/10 text-white" href="https://instagram.com/efremovtrainer" target="_blank">Instagram <ArrowUpRight size={16}/></a><a className="btn border border-white/35 bg-white/10 text-white" href="mailto:efrem77.7735@gmail.com">Email <ArrowUpRight size={16}/></a></div></div><footer className="flex flex-col justify-between gap-4 border-t border-white/20 pt-5 text-xs text-white/60 sm:flex-row"><span>© {new Date().getFullYear()} KE Fitness</span></footer></div></section>
 </main>;
}
